import Footer from "@/components/Footer";
import Header from "@/components/Hedder";
import { ModeToggle } from "@/components/theme/ModeToggle";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Freelancer / Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <>
        <Header />
        <main className="h-screen px-4 sm:px-6 lg:px-8 py-6">
          {/* Main content can go here */}
        </main>
        <Footer />
      </>
    </>
  );
}
