import { ModeToggle } from "@/components/theme/ModeToggle";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Freelancer / Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="min-h-screen flex flex-col bg-gradient-to-br from-gray-50 via-white to-gray-200 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900 relative overflow-hidden">
        <section className="flex flex-1 flex-col justify-center items-center text-center px-4 py-16 relative z-10">
          <div className="max-w-2xl w-full mx-auto bg-white/80 dark:bg-gray-900/80 rounded-3xl shadow-2xl border-4 border-transparent bg-clip-padding p-8 md:p-12 animate-gradient-border">
            <div className="flex justify-center mb-6">
              <span className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-tr from-[#00bcd4] to-cyan-400 shadow-lg">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width={30}
                  height={30}
                  viewBox="0 0 20 20"
                >
                  <path
                    fill="currentColor"
                    d="M9 12H1v6a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-6h-8v2H9zm0-1H0V5c0-1.1.9-2 2-2h4V2a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v1h4a2 2 0 0 1 2 2v6h-9V9H9zm3-8V2H8v1z"
                    strokeWidth={0.5}
                    stroke="currentColor"
                  ></path>
                </svg>
              </span>
            </div>
            <h1 className="text-4xl md:text-5xl font-extrabold mb-4 text-gray-900 dark:text-white drop-shadow-lg">
              Welcome to Your Freelancer Portfolio
            </h1>
            <p className="text-lg md:text-xl text-gray-700 dark:text-gray-300 mb-8">
              Showcase your{" "}
              <span className="font-semibold text-[#00bcd4] dark:text-cyan-400">
                skills
              </span>
              ,{" "}
              <span className="font-semibold text-[#00bcd4] dark:text-cyan-400">
                projects
              </span>
              , and{" "}
              <span className="font-semibold text-[#00bcd4] dark:text-cyan-400">
                services
              </span>
              .<br />
              Ready to get started?
            </p>
            <Link
              href="/auth"
              className="inline-block px-10 py-4 rounded-xl bg-gradient-to-tr from-[#00bcd4] to-cyan-400 text-white font-bold shadow-xl hover:scale-105 hover:shadow-2xl transition-all duration-200 text-xl tracking-wide"
            >
              Go to Login
            </Link>
            <div className=" absolute  top-4 right-4">
              <ModeToggle />
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
