import { ModeToggle } from "@/components/ModeToggle";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Freelancer / Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <>
        <p className="text-2xl font-bold dark:text-yellow-300">hello world</p>
        <ModeToggle />
      </>
    </>
  );
}
